name: Deploy Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Action to checkout the code

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Action to set up Node.js

      - name: Install dependencies
        run: npm install  # Custom command to install dependencies

      - name: Run tests
        run: npm test  # Custom command to run tests
  
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Action to checkout the code

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Action to set up Node.js

      - name: Install dependencies
        run: npm install  # Custom command to install dependencies

      - name: Build projecy
        run: npm run build

      - name: Deploy
        run: echo "Deploying..."